---
# Create a resource group
- name: Azure | Create a resource group
  azure_rm_resourcegroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"  
    name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"
    state: absent

# # ----------------------- Destroy Tower Instances -----------------------
# - name: Get ec2 Tower instance information
#   ec2_instance_facts:
#     region: "{{ region }}"
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "{{ name_prefix + '-s' + item + '-tower'}}"
#   with_sequence: count={{ user_count }}
#   register: ec2_tower_instances

# - name: Terminate Tower Instances
#   ec2:
#     region: "{{ region }}"
#     state: "absent"
#     instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
#   with_items:
#     - "{{ ec2_tower_instances.results }}"
#   when: item.instances.0 is defined and item.instances.0.instance_id is defined

# # ----------------------- Destroy Gitlab Instances -----------------------
# - name: Get ec2 Gitlab instance information
#   ec2_instance_facts:
#     region: "{{ region }}"
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "{{ name_prefix }}-gitlab"
#   register: ec2_gitlab_instances

# - name: Terminate Gitlab Instances
#   ec2:
#     region: "{{ region }}"
#     state: "absent"
#     instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
#   with_items:
#     - "{{ ec2_gitlab_instances }}"
#   when: item.instances.0 is defined

# # ----------------------- Destroy DC Instances -----------------------
# - name: Get ec2 DC instance information
#   ec2_instance_facts:
#     region: "{{ region }}"
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "{{ name_prefix }}-windc"
#   register: ec2_dc_instances

# - name: Terminate DC Instances
#   ec2:
#     region: "{{ region }}"
#     state: "absent"
#     instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
#   with_items:
#     - "{{ ec2_dc_instances }}"
#   when: item.instances.0 is defined

# # ----------------------- Destroy Windows Instances -----------------------
# - name: Get ec2 Windows instance information
#   ec2_instance_facts:
#     region: "{{ region }}"
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "{{ name_prefix + '-s' + item + 'win1'}}"
#   with_sequence: count={{user_count}}
#   register: ec2_windows_instances

# - name: Terminate Windows Instances
#   ec2:
#     region: "{{ region }}"
#     state: "absent"
#     instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
#   with_items:
#     - "{{ ec2_windows_instances.results }}"
#   when: item.instances.0 is defined and item.instances.0.instance_id is defined

# # ----------------------- Destroy Workstation Instances -----------------------
# - name: Get ec2 Workstation instance information
#   ec2_instance_facts:
#     region: "{{ region }}"
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "{{ name_prefix + '-s' + item + 'workstation'}}"
#   with_sequence: count={{user_count}}
#   register: ec2_workstation_instances

# - name: Terminate Workstation Instances
#   ec2:
#     region: "{{ region }}"
#     state: "absent"
#     instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
#   with_items:
#     - "{{ ec2_workstation_instances.results }}"
#   when: item.instances.0 is defined and item.instances.0.instance_id is defined

# ################### Remove Security Groups ###################

# - name: Remove Tower security group   
#   ec2_group:  
#     name: "{{ name_prefix }}-towersg"
#     state: absent
#   register: result
#   until: result|success
#   retries: 20
#   delay: 10

# - name: Remove Gitlab security group   
#   ec2_group:  
#     name: "{{ name_prefix }}-gitlabsg"
#     state: absent
#   register: result
#   until: result|success
#   retries: 20
#   delay: 10

# - name: Remove DC security group   
#   ec2_group:  
#     name: "{{ name_prefix }}-windcsg"
#     state: absent
#   register: result
#   until: result|success
#   retries: 20
#   delay: 10

# - name: Remove Web security group   
#   ec2_group:  
#     name: "{{ name_prefix }}-websg"
#     state: absent
#   register: result
#   until: result|success
#   retries: 20
#   delay: 10

# - name: Remove Windows security group   
#   ec2_group:  
#     name: "{{ name_prefix }}-windowssg"
#     state: absent
#   register: result
#   until: result|success
#   retries: 20
#   delay: 10
